<a href="https://colab.research.google.com/github/sanchi23002/pytorch_projects_/blob/main/pytorch_training_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [ ]:
df.drop(columns=['id', 'Unnamed: 32'], inplace = True)
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [ ]:
df.shape

(569, 31)

**Test Train Split**

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0], test_size=0.2)

**Scaling of the features(X)**

In [ ]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [ ]:
x_test

array([[ 1.5134401 ,  1.33935245,  1.75924192, ...,  1.04670656,
         0.47918385,  1.02626414],
       [-0.16450542, -0.64235782, -0.1886178 , ..., -0.30863777,
        -1.36449967, -0.3786803 ],
       [-0.10953824, -1.22909487, -0.0838625 , ..., -0.2911736 ,
         0.29775755, -0.0822489 ],
       ...,
       [ 1.57997931, -0.22056693,  1.54047582, ...,  1.80296749,
         1.15585493, -0.29282858],
       [ 1.30514341,  0.65836045,  1.24598299, ...,  0.44169782,
         0.36967428, -0.38839936],
       [ 1.92714046,  2.40678973,  2.08318404, ...,  2.42356925,
         1.96818712,  2.19795108]])

In [ ]:
y_train

414    M
43     M
389    M
377    B
457    B
      ..
277    M
378    B
172    M
6      M
502    B
Name: diagnosis, Length: 455, dtype: object

In [ ]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

**Numpy  array to pytorch tensor**

In [ ]:
x_train = torch.from_numpy(x_train.astype(np.float32)) ## pytorch prefer float32 forcumputation of neural network
x_test = torch.from_numpy(x_test.astype(np.float32))
y_train = torch.from_numpy(y_train.astype(np.float32))
y_test = torch.from_numpy(y_test.astype(np.float32))

In [ ]:
print(x_train.shape)
print(y_train.shape)

torch.Size([455, 30])
torch.Size([455])

**Defining the model**

In [ ]:
import torch.nn as nn

class NeuralNetwork(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)## it is a fully connected neuron , take all features as input and 1 output
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

**Important parameters**

In [ ]:
learning_rate = 0.1
epoch = 100

**Loss function**

In [ ]:
loss = nn.BCELoss()

**Training pipeline**

In [23]:
## always first create object(model)
model = NeuralNetwork(x_train.shape[1])

## defining optimizer
optimizer = torch.optim.SGD(model.parameters(),lr = learning_rate) ## batch gradient decent, w = w - n(x(i)*(ycap - y)) , b = b - n(ycap-y)

for i in range(epoch):
  y_pred = model(x_train)
  loss_found = loss(y_pred,y_train.view(-1,1))

  ##  gradient clearance
  optimizer.zero_grad()

  ## Backward Pass
  loss_found.backward()

  ##Parameter update
  optimizer.step()

  ## Print loss in each epoch.
  print("epoch",(i+1),"   loss: ",loss_found.item())

epoch 1    loss:  0.706853449344635
epoch 2    loss:  0.5497340559959412
epoch 3    loss:  0.4650958776473999
epoch 4    loss:  0.4119578003883362
epoch 5    loss:  0.37480080127716064
epoch 6    loss:  0.3469424545764923
epoch 7    loss:  0.3250293433666229
epoch 8    loss:  0.30718156695365906
epoch 9    loss:  0.2922569811344147
epoch 10    loss:  0.27951839566230774
epoch 11    loss:  0.26846665143966675
epoch 12    loss:  0.2587505877017975
epoch 13    loss:  0.2501148283481598
epoch 14    loss:  0.2423688918352127
epoch 15    loss:  0.23536716401576996
epoch 16    loss:  0.22899602353572845
epoch 17    loss:  0.22316542267799377
epoch 18    loss:  0.21780267357826233
epoch 19    loss:  0.21284843981266022
epoch 20    loss:  0.2082536369562149
epoch 21    loss:  0.20397718250751495
epoch 22    loss:  0.19998440146446228
epoch 23    loss:  0.19624577462673187
epoch 24    loss:  0.19273591041564941
epoch 25    loss:  0.18943291902542114
epoch 26    loss:  0.18631769716739655
epoch 27    loss:  0.1833735555410385
epoch 28    loss:  0.1805858016014099
epoch 29    loss:  0.1779414415359497
epoch 30    loss:  0.17542895674705505
epoch 31    loss:  0.173038050532341
epoch 32    loss:  0.17075951397418976
epoch 33    loss:  0.16858512163162231
epoch 34    loss:  0.16650740802288055
epoch 35    loss:  0.16451962292194366
epoch 36    loss:  0.16261573135852814
epoch 37    loss:  0.16079013049602509
epoch 38    loss:  0.15903782844543457
epoch 39    loss:  0.15735416114330292
epoch 40    loss:  0.15573495626449585
epoch 41    loss:  0.15417632460594177
epoch 42    loss:  0.15267474949359894
epoch 43    loss:  0.1512269377708435
epoch 44    loss:  0.14982983469963074
epoch 45    loss:  0.14848071336746216
epoch 46    loss:  0.14717695116996765
epoch 47    loss:  0.1459161788225174
epoch 48    loss:  0.14469614624977112
epoch 49    loss:  0.14351482689380646
epoch 50    loss:  0.14237026870250702
epoch 51    loss:  0.14126066863536835
epoch 52    loss:  0.14018437266349792
epoch 53    loss:  0.1391398310661316
epoch 54    loss:  0.13812552392482758
epoch 55    loss:  0.13714011013507843
epoch 56    loss:  0.1361822932958603
epoch 57    loss:  0.13525086641311646
epoch 58    loss:  0.1343446969985962
epoch 59    loss:  0.13346268236637115
epoch 60    loss:  0.13260383903980255
epoch 61    loss:  0.13176719844341278
epoch 62    loss:  0.1309518814086914
epoch 63    loss:  0.13015702366828918
epoch 64    loss:  0.12938180565834045
epoch 65    loss:  0.12862548232078552
epoch 66    loss:  0.12788733839988708
epoch 67    loss:  0.12716667354106903
epoch 68    loss:  0.12646286189556122
epoch 69    loss:  0.12577524781227112
epoch 70    loss:  0.12510329484939575
epoch 71    loss:  0.12444640696048737
epoch 72    loss:  0.12380408495664597
epoch 73    loss:  0.12317578494548798
epoch 74    loss:  0.12256105989217758
epoch 75    loss:  0.12195944041013718
epoch 76    loss:  0.12137048691511154
epoch 77    loss:  0.12079378217458725
epoch 78    loss:  0.12022890895605087
epoch 79    loss:  0.11967553943395615
epoch 80    loss:  0.11913326382637024
epoch 81    loss:  0.1186017394065857
epoch 82    loss:  0.11808064579963684
epoch 83    loss:  0.11756964027881622
epoch 84    loss:  0.11706842482089996
epoch 85    loss:  0.11657672375440598
epoch 86    loss:  0.11609424650669098
epoch 87    loss:  0.11562070995569229
epoch 88    loss:  0.11515584588050842
epoch 89    loss:  0.11469943821430206
epoch 90    loss:  0.11425123363733292
epoch 91    loss:  0.11381097882986069
epoch 92    loss:  0.11337847262620926
epoch 93    loss:  0.11295351386070251
epoch 94    loss:  0.11253587156534195
epoch 95    loss:  0.11212535202503204
epoch 96    loss:  0.11172178387641907
epoch 97    loss:  0.1113249659538269
epoch 98    loss:  0.11093470454216003
epoch 99    loss:  0.1105508804321289
epoch 100    loss:  0.11017327755689621

Evaluation

In [32]:
## Model Evaluation
with torch.no_grad():
  y_pred = model(x_test)
  y_pred = (y_pred>=0.5).float()
  accuracy = (y_pred==y_test).float().mean()
  print("accuracy" , accuracy.item())

accuracy 0.5003077983856201