<a href="https://colab.research.google.com/github/sanchi23002/pytorch_projects_/blob/main/pytorch_training_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import torch
import pandas as pd

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler## normalize the value in between 0 to 1
from sklearn.preprocessing import LabelEncoder## used for making binary level on the output

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head() ## show first five rows of the column

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [4]:
df.shape

(569, 33)

In [5]:
df.drop(columns=['id','Unnamed: 32'], inplace = True)

In [6]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [7]:
df.shape

(569, 31)

In [8]:
## train test split
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:, 1:],df.iloc[:, 0], test_size= 0.2)## iloc tell the location
## in both cases all rows are including for the study but for x we are taking from the second column , and for y we are taking only the first column

In [9]:
x_train.head()

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
443,10.570,18.32,66.82,340.9,0.08142,0.04462,0.019930,0.011110,0.2372,0.05768,...,10.94,23.31,69.35,366.3,0.09794,0.06542,0.039860,0.022220,0.2699,0.06736
285,12.580,18.40,79.83,489.0,0.08393,0.04216,0.001860,0.002924,0.1697,0.05855,...,13.50,23.08,85.56,564.1,0.10380,0.06624,0.005579,0.008772,0.2505,0.06431
424,9.742,19.12,61.93,289.7,0.10750,0.08333,0.008934,0.019670,0.2538,0.07029,...,11.21,23.17,71.79,380.9,0.13980,0.13520,0.020850,0.045890,0.3196,0.08009
346,12.060,18.90,76.66,445.3,0.08386,0.05794,0.007510,0.008488,0.1555,0.06048,...,13.64,27.06,86.54,562.6,0.12890,0.13520,0.045060,0.050930,0.2880,0.08083
450,11.870,21.54,76.83,432.0,0.06613,0.10640,0.087770,0.023860,0.1349,0.06612,...,12.79,28.18,83.51,507.2,0.09457,0.33990,0.321800,0.087500,0.2305,0.09952

In [10]:
y_train

443    B
285    B
424    B
346    B
450    B
      ..
536    M
244    M
80     B
275    B
410    B
Name: diagnosis, Length: 455, dtype: object

In [11]:
## label_encoding
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)## fit tells what to lebel
y_test = encoder.transform(y_test)## transform tell follow the label that are taken by fit
##Number assign occurs alphabetically so B->benign is equal to 0 and M-> malignant is equal to one.

In [12]:
y_train

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0])

In [13]:
## scaling
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [14]:
## numpy array to pytorch tensor
x_train_tensor = torch.from_numpy(x_train)
x_test_tensor = torch.from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [15]:
print(x_train_tensor.shape)
print(y_train_tensor.shape)

torch.Size([455, 30])
torch.Size([455])

In [16]:
## defining the model

class my_neural_network():
  def __init__(self,x):
    self.weights = torch.rand(x.shape[1],1,dtype = torch.float64, requires_grad= True)
  ## matrix multiplication is done in X and W , so W row must be equal to columns of x and the output of eash row is one prediction as it is binary classification
    self.bias = torch.ones(1,dtype=torch.float32, requires_grad=True)

  def forward(self,x):
    z = torch.matmul(x, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(slef, y_pred, y):
    epsilon = 1e-8
    y_pred = torch.clamp(y_pred, epsilon , 1 - epsilon)
    loss = -y*torch.log(y_pred) - (1-y)*torch.log(1-y_pred)
    mean_loss = torch.mean(loss)
    return mean_loss

In [34]:
learning_rate = 0.01
epoch = 3000

In [35]:
## training pipeline

# create model
model = my_neural_network(x_train_tensor)

for i in range(epoch):
  y_pred = model.forward(x_train_tensor)
  loss = model.loss_function(y_pred, y_train_tensor)
  loss.backward()
  with torch.no_grad():
    model.weights -= learning_rate*model.weights.grad
    model.bias -= learning_rate*model.bias.grad
  model.weights.grad.zero_()
  model.bias.grad.zero_()
  print(f'Epoch : {i+1}, loss : {loss.item()}')

Epoch : 1, loss : 3.4445150919991883
Epoch : 2, loss : 3.4310316045097156
Epoch : 3, loss : 3.4175701380578674
Epoch : 4, loss : 3.4041308645323833
Epoch : 5, loss : 3.3907139612156665
Epoch : 6, loss : 3.3773196071374225
Epoch : 7, loss : 3.363947979702923
Epoch : 8, loss : 3.3505992618575533
Epoch : 9, loss : 3.3372736349415586
Epoch : 10, loss : 3.323971286262413
Epoch : 11, loss : 3.3106924053707463
Epoch : 12, loss : 3.2974371804635867
Epoch : 13, loss : 3.2842058059681247
Epoch : 14, loss : 3.2709984789197404
Epoch : 15, loss : 3.2578153951413467
Epoch : 16, loss : 3.244554172484426
Epoch : 17, loss : 3.2308973520964135
Epoch : 18, loss : 3.217256577681245
Epoch : 19, loss : 3.203374606316512
Epoch : 20, loss : 3.189258851345751
Epoch : 21, loss : 3.175170677642862
Epoch : 22, loss : 3.1611103300286314
Epoch : 23, loss : 3.147078066234802
Epoch : 24, loss : 3.133029716023419
Epoch : 25, loss : 3.11876502832552
Epoch : 26, loss : 3.1045298758059725
Epoch : 27, loss : 3.0903245489563345
Epoch : 28, loss : 3.0761493337878965
Epoch : 29, loss : 3.0620045210593987
Epoch : 30, loss : 3.0478904110054015
Epoch : 31, loss : 3.0338073040189095
Epoch : 32, loss : 3.0197555101470344
Epoch : 33, loss : 3.005735339696112
Epoch : 34, loss : 2.9917471126954216
Epoch : 35, loss : 2.97779114944605
Epoch : 36, loss : 2.9638677752380933
Epoch : 37, loss : 2.9499773252880064
Epoch : 38, loss : 2.9361201349843014
Epoch : 39, loss : 2.922296549743245
Epoch : 40, loss : 2.9085069151063827
Epoch : 41, loss : 2.894751581599713
Epoch : 42, loss : 2.881030909816144
Epoch : 43, loss : 2.8673452603215965
Epoch : 44, loss : 2.853695003773695
Epoch : 45, loss : 2.840080510656502
Epoch : 46, loss : 2.826502156314492
Epoch : 47, loss : 2.81296032609544
Epoch : 48, loss : 2.7993748186376997
Epoch : 49, loss : 2.7856640048859145
Epoch : 50, loss : 2.7719911932503347
Epoch : 51, loss : 2.758356793503267
Epoch : 52, loss : 2.7447612255750706
Epoch : 53, loss : 2.731204908604829
Epoch : 54, loss : 2.7176882662556396
Epoch : 55, loss : 2.704211726478006
Epoch : 56, loss : 2.6907757271594286
Epoch : 57, loss : 2.6773507126705747
Epoch : 58, loss : 2.663709704454154
Epoch : 59, loss : 2.6501113916876124
Epoch : 60, loss : 2.6365562345772835
Epoch : 61, loss : 2.6230168940043965
Epoch : 62, loss : 2.609211623791483
Epoch : 63, loss : 2.5953324917288545
Epoch : 64, loss : 2.5812958906343173
Epoch : 65, loss : 2.5673074339097126
Epoch : 66, loss : 2.553367663042579
Epoch : 67, loss : 2.539477117259716
Epoch : 68, loss : 2.525568766472651
Epoch : 69, loss : 2.5114827891790092
Epoch : 70, loss : 2.497448509879014
Epoch : 71, loss : 2.483466500722955
Epoch : 72, loss : 2.4695373434855594
Epoch : 73, loss : 2.455661609715381
Epoch : 74, loss : 2.441839880012518
Epoch : 75, loss : 2.4280727439694245
Epoch : 76, loss : 2.4143607801543694
Epoch : 77, loss : 2.4006342054689975
Epoch : 78, loss : 2.38675144154245
Epoch : 79, loss : 2.3729262894806182
Epoch : 80, loss : 2.3591593669355544
Epoch : 81, loss : 2.345451285892074
Epoch : 82, loss : 2.331802659062028
Epoch : 83, loss : 2.3182141067614035
Epoch : 84, loss : 2.3046862353899473
Epoch : 85, loss : 2.291219658181671
Epoch : 86, loss : 2.277814995099902
Epoch : 87, loss : 2.264306396592978
Epoch : 88, loss : 2.2506265868492483
Epoch : 89, loss : 2.2370127261074546
Epoch : 90, loss : 2.2234654673935554
Epoch : 91, loss : 2.2099854541708566
Epoch : 92, loss : 2.196446313863548
Epoch : 93, loss : 2.1826571413735336
Epoch : 94, loss : 2.16894020758485
Epoch : 95, loss : 2.1552961908941817
Epoch : 96, loss : 2.141725765165608
Epoch : 97, loss : 2.1282296072967695
Epoch : 98, loss : 2.114808372992766
Epoch : 99, loss : 2.1014627278501687
Epoch : 100, loss : 2.0881933231602603
Epoch : 101, loss : 2.075000811388567
Epoch : 102, loss : 2.0617979760093923
Epoch : 103, loss : 2.0484881522270992
Epoch : 104, loss : 2.0352583975010097
Epoch : 105, loss : 2.0221093501427507
Epoch : 106, loss : 2.008912763657897
Epoch : 107, loss : 1.9955119958518226
Epoch : 108, loss : 1.982196297858838
Epoch : 109, loss : 1.968966311802526
Epoch : 110, loss : 1.9558015494412468
Epoch : 111, loss : 1.9424484749444055
Epoch : 112, loss : 1.9291839865838942
Epoch : 113, loss : 1.916008706231276
Epoch : 114, loss : 1.9029232520221382
Epoch : 115, loss : 1.8899282293004962
Epoch : 116, loss : 1.877024220811926
Epoch : 117, loss : 1.8642117955575648
Epoch : 118, loss : 1.8513769973524328
Epoch : 119, loss : 1.8383643057760992
Epoch : 120, loss : 1.8254475032986333
Epoch : 121, loss : 1.8126271434207681
Epoch : 122, loss : 1.7999037742295245
Epoch : 123, loss : 1.7872779190626895
Epoch : 124, loss : 1.774750105453536
Epoch : 125, loss : 1.762320826364425
Epoch : 126, loss : 1.7499905690934805
Epoch : 127, loss : 1.73775980561685
Epoch : 128, loss : 1.72562898251416
Epoch : 129, loss : 1.7135985507591118
Epoch : 130, loss : 1.7016689360366177
Epoch : 131, loss : 1.689840538319689
Epoch : 132, loss : 1.6781137622103226
Epoch : 133, loss : 1.6664889867161499
Epoch : 134, loss : 1.6549665751542535
Epoch : 135, loss : 1.643546875118358
Epoch : 136, loss : 1.6322302183885131
Epoch : 137, loss : 1.6210169208397054
Epoch : 138, loss : 1.6099072929250122
Epoch : 139, loss : 1.5989016186094362
Epoch : 140, loss : 1.5880001762821954
Epoch : 141, loss : 1.577203217401574
Epoch : 142, loss : 1.5665109767827332
Epoch : 143, loss : 1.5559236832794077
Epoch : 144, loss : 1.545441538010046
Epoch : 145, loss : 1.535064735758703
Epoch : 146, loss : 1.5247934539965529
Epoch : 147, loss : 1.51462784144572
Epoch : 148, loss : 1.50456803977084
Epoch : 149, loss : 1.494614172349535
Epoch : 150, loss : 1.4847663326104354
Epoch : 151, loss : 1.4750246173474508
Epoch : 152, loss : 1.4653890813925268
Epoch : 153, loss : 1.4558597708742593
Epoch : 154, loss : 1.4464367116115777
Epoch : 155, loss : 1.4371199086568842
Epoch : 156, loss : 1.4279093458243357
Epoch : 157, loss : 1.4188049968874954
Epoch : 158, loss : 1.4098067902247473
Epoch : 159, loss : 1.4009146547870692
Epoch : 160, loss : 1.3921284847462623
Epoch : 161, loss : 1.383448150540782
Epoch : 162, loss : 1.374873510307088
Epoch : 163, loss : 1.3664043737156464
Epoch : 164, loss : 1.3580405610408939
Epoch : 165, loss : 1.3497818431557362
Epoch : 166, loss : 1.341627964695462
Epoch : 167, loss : 1.3335786557822562
Epoch : 168, loss : 1.3256336074075792
Epoch : 169, loss : 1.3177924952715467
Epoch : 170, loss : 1.310054967353863
Epoch : 171, loss : 1.3024206311601076
Epoch : 172, loss : 1.2948890903737973
Epoch : 173, loss : 1.2874598827855208
Epoch : 174, loss : 1.2801325542769013
Epoch : 175, loss : 1.2729066092365084
Epoch : 176, loss : 1.2657815101220842
Epoch : 177, loss : 1.2587567150311347
Epoch : 178, loss : 1.2518316274625043
Epoch : 179, loss : 1.2450056339929054
Epoch : 180, loss : 1.238278104644369
Epoch : 181, loss : 1.231648354878927
Epoch : 182, loss : 1.2251156838656485
Epoch : 183, loss : 1.2186793621649419
Epoch : 184, loss : 1.2123386450394609
Epoch : 185, loss : 1.2060927342750483
Epoch : 186, loss : 1.1999408302251617
Epoch : 187, loss : 1.1938820938032053
Epoch : 188, loss : 1.1879156469350132
Epoch : 189, loss : 1.182040612399848
Epoch : 190, loss : 1.1762560757116944
Epoch : 191, loss : 1.170561112127202
Epoch : 192, loss : 1.1649547482304436
Epoch : 193, loss : 1.1594360022212764
Epoch : 194, loss : 1.1540038852089844
Epoch : 195, loss : 1.1486573759681284
Epoch : 196, loss : 1.1433954219147238
Epoch : 197, loss : 1.1382169801658224
Epoch : 198, loss : 1.1331209924295238
Epoch : 199, loss : 1.1281063594832261
Epoch : 200, loss : 1.1231719823807742
Epoch : 201, loss : 1.1183167505055536
Epoch : 202, loss : 1.1135395563684933
Epoch : 203, loss : 1.108839256621509
Epoch : 204, loss : 1.1042147271249159
Epoch : 205, loss : 1.0996648104356106
Epoch : 206, loss : 1.0951883710420842
Epoch : 207, loss : 1.090784256217954
Epoch : 208, loss : 1.086451297138722
Epoch : 209, loss : 1.0821883508393049
Epoch : 210, loss : 1.077994247155216
Epoch : 211, loss : 1.073867844245588
Epoch : 212, loss : 1.0698079753081238
Epoch : 213, loss : 1.0658134904863474
Epoch : 214, loss : 1.0618832443495274
Epoch : 215, loss : 1.0580160969040877
Epoch : 216, loss : 1.0542109145592773
Epoch : 217, loss : 1.0504665573000116
Epoch : 218, loss : 1.046781920732614
Epoch : 219, loss : 1.0431558820285562
Epoch : 220, loss : 1.039587328066103
Epoch : 221, loss : 1.036075183754952
Epoch : 222, loss : 1.0326183576784902
Epoch : 223, loss : 1.0292157839925238
Epoch : 224, loss : 1.0258664092746181
Epoch : 225, loss : 1.0225691792284093
Epoch : 226, loss : 1.0193230667869086
Epoch : 227, loss : 1.016127044941946
Epoch : 228, loss : 1.0129801147980402
Epoch : 229, loss : 1.0098812921480118
Epoch : 230, loss : 1.0068295939293173
Epoch : 231, loss : 1.0038240523294741
Epoch : 232, loss : 1.0008637289268285
Epoch : 233, loss : 0.9979477010820189
Epoch : 234, loss : 0.9950750482308498
Epoch : 235, loss : 0.9922448658813194
Epoch : 236, loss : 0.9894562796377543
Epoch : 237, loss : 0.9867084175414871
Epoch : 238, loss : 0.9840004239967248
Epoch : 239, loss : 0.9813314737177266
Epoch : 240, loss : 0.9787007439717207
Epoch : 241, loss : 0.9761074423474934
Epoch : 242, loss : 0.9735507789449076
Epoch : 243, loss : 0.9710299802004944
Epoch : 244, loss : 0.9685442888197694
Epoch : 245, loss : 0.966092963691034
Epoch : 246, loss : 0.9636752936847826
Epoch : 247, loss : 0.9612905697474929
Epoch : 248, loss : 0.9589380986464789
Epoch : 249, loss : 0.956617202821192
Epoch : 250, loss : 0.9543272202215117
Epoch : 251, loss : 0.9520675180240237
Epoch : 252, loss : 0.9498374507927327
Epoch : 253, loss : 0.9476364158030183
Epoch : 254, loss : 0.9454637973322001
Epoch : 255, loss : 0.943319021937025
Epoch : 256, loss : 0.9412015166274078
Epoch : 257, loss : 0.9391107225025118
Epoch : 258, loss : 0.9370460806616243
Epoch : 259, loss : 0.9350070735251541
Epoch : 260, loss : 0.9329931830420284
Epoch : 261, loss : 0.931003890451917
Epoch : 262, loss : 0.929038717537392
Epoch : 263, loss : 0.9270971710535018
Epoch : 264, loss : 0.9251787977608761
Epoch : 265, loss : 0.9232831289083647
Epoch : 266, loss : 0.9214097214070881
Epoch : 267, loss : 0.9195581437621764
Epoch : 268, loss : 0.9177279758131135
Epoch : 269, loss : 0.9159188084743196
Epoch : 270, loss : 0.9141302297168425
Epoch : 271, loss : 0.9123618518420858
Epoch : 272, loss : 0.9106132974563345
Epoch : 273, loss : 0.9088841992161723
Epoch : 274, loss : 0.9071741995760034
Epoch : 275, loss : 0.9054829368310412
Epoch : 276, loss : 0.9038100723013492
Epoch : 277, loss : 0.9021552763653968
Epoch : 278, loss : 0.9005182282187274
Epoch : 279, loss : 0.8988986019758565
Epoch : 280, loss : 0.8972960937777095
Epoch : 281, loss : 0.8957104078818027
Epoch : 282, loss : 0.8941412428130027
Epoch : 283, loss : 0.892588318410177
Epoch : 284, loss : 0.8910513619632826
Epoch : 285, loss : 0.889530094416344
Epoch : 286, loss : 0.8880242573501559
Epoch : 287, loss : 0.8865335856141708
Epoch : 288, loss : 0.8850578342646931
Epoch : 289, loss : 0.8835967647869266
Epoch : 290, loss : 0.8821501313908952
Epoch : 291, loss : 0.8807177078799844
Epoch : 292, loss : 0.8792992604444683
Epoch : 293, loss : 0.8778945744815891
Epoch : 294, loss : 0.8765034409090794
Epoch : 295, loss : 0.8751256425596121
Epoch : 296, loss : 0.8737609742145168
Epoch : 297, loss : 0.8724092357107422
Epoch : 298, loss : 0.8710702317870995
Epoch : 299, loss : 0.8697437719349033
Epoch : 300, loss : 0.8684296769313875
Epoch : 301, loss : 0.8671277586529378
Epoch : 302, loss : 0.8658378399948747
Epoch : 303, loss : 0.864559748050404
Epoch : 304, loss : 0.8632933073374189
Epoch : 305, loss : 0.8620383596205705
Epoch : 306, loss : 0.8607947438332246
Epoch : 307, loss : 0.8595622959980853
Epoch : 308, loss : 0.8583408689834986
Epoch : 309, loss : 0.857130305911925
Epoch : 310, loss : 0.8559304599094005
Epoch : 311, loss : 0.8547411807978035
Epoch : 312, loss : 0.8535623347591065
Epoch : 313, loss : 0.8523937778989521
Epoch : 314, loss : 0.8512353759033517
Epoch : 315, loss : 0.8500869973622585
Epoch : 316, loss : 0.8489485071461637
Epoch : 317, loss : 0.8478197859486403
Epoch : 318, loss : 0.8467007040479481
Epoch : 319, loss : 0.8455911343323348
Epoch : 320, loss : 0.8444909587251581
Epoch : 321, loss : 0.8434000615799039
Epoch : 322, loss : 0.8423183296102329
Epoch : 323, loss : 0.8412456453522977
Epoch : 324, loss : 0.8401819000650799
Epoch : 325, loss : 0.8391269807221257
Epoch : 326, loss : 0.8380807828774288
Epoch : 327, loss : 0.837043197700502
Epoch : 328, loss : 0.8360141248070806
Epoch : 329, loss : 0.8349934657482491
Epoch : 330, loss : 0.8339811175571389
Epoch : 331, loss : 0.8329769855255855
Epoch : 332, loss : 0.8319809703480847
Epoch : 333, loss : 0.8309929808616006
Epoch : 334, loss : 0.830012921233276
Epoch : 335, loss : 0.8290406973134289
Epoch : 336, loss : 0.8280762292713794
Epoch : 337, loss : 0.8271194198146912
Epoch : 338, loss : 0.8261701858856028
Epoch : 339, loss : 0.8252284459102902
Epoch : 340, loss : 0.8242941134643073
Epoch : 341, loss : 0.8233671035725487
Epoch : 342, loss : 0.8224473389509995
Epoch : 343, loss : 0.8215347373927513
Epoch : 344, loss : 0.820629218040224
Epoch : 345, loss : 0.8197307075982518
Epoch : 346, loss : 0.8188391277867048
Epoch : 347, loss : 0.8179544078069296
Epoch : 348, loss : 0.8170764718389165
Epoch : 349, loss : 0.8162052452657146
Epoch : 350, loss : 0.8153406608373348
Epoch : 351, loss : 0.8144826462349231
Epoch : 352, loss : 0.8136311302656545
Epoch : 353, loss : 0.8127860428387368
Epoch : 354, loss : 0.8119473210888358
Epoch : 355, loss : 0.8111148970299525
Epoch : 356, loss : 0.8102887098348446
Epoch : 357, loss : 0.8094686874201682
Epoch : 358, loss : 0.8086547709413942
Epoch : 359, loss : 0.8078469024844995
Epoch : 360, loss : 0.8070450128849678
Epoch : 361, loss : 0.8062490460924305
Epoch : 362, loss : 0.8054589408713656
Epoch : 363, loss : 0.8046746368833713
Epoch : 364, loss : 0.8038960746698295
Epoch : 365, loss : 0.8031232016599593
Epoch : 366, loss : 0.8023559540596056
Epoch : 367, loss : 0.8015942809524824
Epoch : 368, loss : 0.8008381321946744
Epoch : 369, loss : 0.8000874464390305
Epoch : 370, loss : 0.7993421691346575
Epoch : 371, loss : 0.7986022524587033
Epoch : 372, loss : 0.7978676433555435
Epoch : 373, loss : 0.7971382895121591
Epoch : 374, loss : 0.7964141393448103
Epoch : 375, loss : 0.7956951419860379
Epoch : 376, loss : 0.7949812531730046
Epoch : 377, loss : 0.7942724175113426
Epoch : 378, loss : 0.7935685920857155
Epoch : 379, loss : 0.7928697287376093
Epoch : 380, loss : 0.7921757799640865
Epoch : 381, loss : 0.7914866989065075
Epoch : 382, loss : 0.7908024393395017
Epoch : 383, loss : 0.7901229556601849
Epoch : 384, loss : 0.7894482028776106
Epoch : 385, loss : 0.7887781424010815
Epoch : 386, loss : 0.7881127246131004
Epoch : 387, loss : 0.7874519120731872
Epoch : 388, loss : 0.7867956563401113
Epoch : 389, loss : 0.7861439210848722
Epoch : 390, loss : 0.7854966647461062
Epoch : 391, loss : 0.7848538463064302
Epoch : 392, loss : 0.7842154195649391
Epoch : 393, loss : 0.7835813503055373
Epoch : 394, loss : 0.7829515990901111
Epoch : 395, loss : 0.7823261269899355
Epoch : 396, loss : 0.7817048955774433
Epoch : 397, loss : 0.7810878669181553
Epoch : 398, loss : 0.7804750035627599
Epoch : 399, loss : 0.7798662685393462
Epoch : 400, loss : 0.7792616309726836
Epoch : 401, loss : 0.7786610491745481
Epoch : 402, loss : 0.778064487559988
Epoch : 403, loss : 0.7774719109917931
Epoch : 404, loss : 0.7768832847734152
Epoch : 405, loss : 0.7762985746420155
Epoch : 406, loss : 0.7757177467616374
Epoch : 407, loss : 0.7751407677165016
Epoch : 408, loss : 0.7745676045044182
Epoch : 409, loss : 0.7739982245303159
Epoch : 410, loss : 0.773432595599885
Epoch : 411, loss : 0.7728706859133301
Epoch : 412, loss : 0.7723124640592315
Epoch : 413, loss : 0.7717578990085133
Epoch : 414, loss : 0.7712069601085145
Epoch : 415, loss : 0.7706596170771626
Epoch : 416, loss : 0.7701158399972446
Epoch : 417, loss : 0.7695755993107783
Epoch : 418, loss : 0.7690388631031077
Epoch : 419, loss : 0.7685056025347566
Epoch : 420, loss : 0.7679757891091678
Epoch : 421, loss : 0.7674493946674396
Epoch : 422, loss : 0.7669263913831533
Epoch : 423, loss : 0.7664067517572853
Epoch : 424, loss : 0.7658904459370548
Epoch : 425, loss : 0.7653774497503104
Epoch : 426, loss : 0.7648677339857742
Epoch : 427, loss : 0.7643612724213573
Epoch : 428, loss : 0.7638580391381775
Epoch : 429, loss : 0.7633580085159583
Epoch : 430, loss : 0.7628611552285013
Epoch : 431, loss : 0.7623674542392387
Epoch : 432, loss : 0.7618768781661343
Epoch : 433, loss : 0.7613894025553235
Epoch : 434, loss : 0.7609050032296532
Epoch : 435, loss : 0.7604236562845152
Epoch : 436, loss : 0.7599453354756499
Epoch : 437, loss : 0.7594700200502524
Epoch : 438, loss : 0.7589976843002246
Epoch : 439, loss : 0.7585283053873056
Epoch : 440, loss : 0.7580618581403951
Epoch : 441, loss : 0.7575983228192774
Epoch : 442, loss : 0.7571376747582823
Epoch : 443, loss : 0.7566798921240696
Epoch : 444, loss : 0.7562249533212942
Epoch : 445, loss : 0.7557728344315762
Epoch : 446, loss : 0.7553235143414159
Epoch : 447, loss : 0.7548769721648816
Epoch : 448, loss : 0.7544331872402523
Epoch : 449, loss : 0.7539921391267155
Epoch : 450, loss : 0.7535538050715411
Epoch : 451, loss : 0.7531181650823687
Epoch : 452, loss : 0.7526851993781473
Epoch : 453, loss : 0.7522548858731505
Epoch : 454, loss : 0.7518272052160143
Epoch : 455, loss : 0.751402138257551
Epoch : 456, loss : 0.7509796660478107
Epoch : 457, loss : 0.7505597673424499
Epoch : 458, loss : 0.7501424235975975
Epoch : 459, loss : 0.7497276164600742
Epoch : 460, loss : 0.749315325290449
Epoch : 461, loss : 0.7489055321249026
Epoch : 462, loss : 0.7484982191821767
Epoch : 463, loss : 0.7480933664032506
Epoch : 464, loss : 0.7476909588325439
Epoch : 465, loss : 0.7472909767742112
Epoch : 466, loss : 0.7468934007263347
Epoch : 467, loss : 0.7464982138142536
Epoch : 468, loss : 0.7461053993307747
Epoch : 469, loss : 0.7457149407338094
Epoch : 470, loss : 0.7453268192245651
Epoch : 471, loss : 0.7449410186002368
Epoch : 472, loss : 0.7445575228162425
Epoch : 473, loss : 0.7441763135808013
Epoch : 474, loss : 0.7437973751751363
Epoch : 475, loss : 0.7434206896397461
Epoch : 476, loss : 0.7430462439600287
Epoch : 477, loss : 0.7426740204843421
Epoch : 478, loss : 0.7423040017277774
Epoch : 479, loss : 0.7419361727409773
Epoch : 480, loss : 0.741570518716046
Epoch : 481, loss : 0.7412070249846188
Epoch : 482, loss : 0.7408456746611555
Epoch : 483, loss : 0.7404864533664638
Epoch : 484, loss : 0.7401293445111111
Epoch : 485, loss : 0.7397743339976283
Epoch : 486, loss : 0.7394214078588336
Epoch : 487, loss : 0.739070549927893
Epoch : 488, loss : 0.7387217465086598
Epoch : 489, loss : 0.7383749840300935
Epoch : 490, loss : 0.7380302467322761
Epoch : 491, loss : 0.7376875213050299
Epoch : 492, loss : 0.7373467945583538
Epoch : 493, loss : 0.7370080511243187
Epoch : 494, loss : 0.7366712769184636
Epoch : 495, loss : 0.7363364591252097
Epoch : 496, loss : 0.7360035839025414
Epoch : 497, loss : 0.7356726375312787
Epoch : 498, loss : 0.7353436064135929
Epoch : 499, loss : 0.7350164782041264
Epoch : 500, loss : 0.7346912395356922
Epoch : 501, loss : 0.7343678771581583
Epoch : 502, loss : 0.7340463790618542
Epoch : 503, loss : 0.7337267310967255
Epoch : 504, loss : 0.7334089214751747
Epoch : 505, loss : 0.7330929373939491
Epoch : 506, loss : 0.7327787661601216
Epoch : 507, loss : 0.7324663963017226
Epoch : 508, loss : 0.7321558142256871
Epoch : 509, loss : 0.731847008669234
Epoch : 510, loss : 0.7315399673605123
Epoch : 511, loss : 0.7312346781317867
Epoch : 512, loss : 0.730931130017388
Epoch : 513, loss : 0.73062930995012
Epoch : 514, loss : 0.7303292071616019
Epoch : 515, loss : 0.7300308098813417
Epoch : 516, loss : 0.7297341064372189
Epoch : 517, loss : 0.7294390863408644
Epoch : 518, loss : 0.7291457370221798

In [36]:
model.bias ## current value of the bias term

tensor([-0.5193], requires_grad=True)

In [37]:
## Evaluation

with torch.no_grad():
  y_pred = model.forward(x_test_tensor)
  y_pred = (y_pred>0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(accuracy.item())

0.6315789222717285